
# Menderbot may send source code in this repo to the enabled APIs.
# If this includes propietary information, make sure you are authorized to do so.
# Set consent to yes if this is OK.
consent: yes
apis:
    openai:
        enabled: yes
        api_key_env_var: OPENAI_API_KEY
        models:
        - gpt-4
        - gpt-4-32k
        - gpt-3.5-turbo
        - gpt-3.5-turbo-16k
        - text-embedding-ada-002
