name: Test

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install build deps
        run: |
          pip install --upgrade wheel build
      - name: Install dependencies
        run: |
          pip install "." ".[dev]"
      - name: tests
        run: |
          python -m pytest --cov --cov-fail-under=50
      - name: type-checking
        run: |
          python -m mypy menderbot --install-types
      - name: build whl
        run: |
          python -m build
          find ./dist/*.whl | xargs pip install
